### ISSUE TITLE
UnboundLocalError: local variable 'test_loss' referenced before assignment

### ISSUE THREAD

**Issue by simonibs** [karpathy/minGPT#36]
When the training process finished the first epoch and saved the model, it threw out the error:
```
epoch 1 iter 8713: train loss 0.25403. lr 3.000169e-04: 100%|██████████| 8714/8714 [4:12:50<00:00,  1.74s/it]  
Traceback (most recent call last):
  File "try.py", line 105, in <module>
    trainer.train()
  File "/home/ec2-user/minGPT/mingpt/trainer.py", line 129, in train
    best_loss = test_loss
UnboundLocalError: local variable 'test_loss' referenced before assignment
```

Environment: Python3 + pytorch 1.6

**Comment by tawnkramer** [comment]
you have to prepare a test set and pass it into the trainer. I made a method of class CharDataset to split it into two sets:
```
def split(self, perc):
        iTrim = round(len(self.data) * perc)
        iKeep = len(self.data) - iTrim
        test = self.data[iKeep:]
        train = self.data[:iKeep]
        self.data = train

        test_set = CharDataset(test, self.block_size)
        # maintain same dict
        test_set.stoi = self.stoi
        test_set.itos = self.itos

        return test_set
```

then

```
test_dataset = train_dataset.split(0.2) # take last 20% for a test set
tconf.ckpt_path = "mycheck.ckpt"
trainer = Trainer(model, train_dataset, test_dataset, tconf)
```

**Comment by simonibs** [comment]
Yeh, that makes sense. Thanks @tawnkramer.
